## Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

## Read Data

In [2]:
df = pd.read_csv('FoodBalanceSheets_E_Africa_NOFLAG.csv')

In [3]:
df

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
...,...,...,...,...,...,...,...,...,...,...,...,...
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60943 entries, 0 to 60942
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Area Code     60943 non-null  int64
 1   Area          60943 non-null  object
 2   Item Code     60943 non-null  int64
 3   Item          60943 non-null  object
 4   Element Code  60943 non-null  int64
 5   Element       60943 non-null  object
 6   Unit          60943 non-null  object
 7   Y2014         59354 non-null  float64
 8   Y2015         59395 non-null  float64
 9   Y2016         59408 non-null  float64
 10  Y2017         59437 non-null  float64
 11  Y2018         59507 non-null  float64
dtypes: float64(5), int64(3), object(4)
memory usage: 5.6+ MB

In [4]:
df.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [5]:
df.describe(include='all')

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943,60943.000000,60943,60943.000000,60943,60943,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
unique,NaN,49,NaN,119,NaN,18,5,NaN,NaN,NaN,NaN,NaN
top,NaN,Kenya,NaN,Milk - Excluding Butter,NaN,Domestic supply quantity,1000 tonnes,NaN,NaN,NaN,NaN,NaN
freq,NaN,1560,NaN,1262,NaN,5295,40933,NaN,NaN,NaN,NaN,NaN
mean,134.265576,NaN,2687.176706,NaN,3814.856456,NaN,NaN,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,NaN,146.055739,NaN,2212.007033,NaN,NaN,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,NaN,2501.000000,NaN,511.000000,NaN,NaN,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,NaN,2562.000000,NaN,684.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,NaN,2630.000000,NaN,5142.000000,NaN,NaN,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,NaN,2775.000000,NaN,5511.000000,NaN,NaN,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,NaN,2961.000000,NaN,5911.000000,NaN,NaN,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [6]:
df.isnull().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [11]:
pd.set_option('display.max_rows',None)

## What is the total sum of Animal Fat Produced in 2014 and 2017 respectively?

In [15]:
#perform a groupby sum aggregration on 'Item'

df.groupby('Item').sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Item,,,,,,,,
"Alcohol, Non-Food",38447,752497,1515090,2403.00,2180.00,2223.00,2348.00,2293.00
Alcoholic Beverages,75016,1649136,2171381,102410.11,98783.72,96958.75,95581.06,97847.27
Animal Products,18060,397035,90990,11935.65,11811.73,11661.69,11547.65,11578.61
Animal fats,85279,1882494,2567303,209460.54,200675.72,183314.22,269617.53,269648.27
Apples and products,69280,1352989,1920418,9499.23,10559.15,9853.26,10198.90,9640.51
"Aquatic Animals, Others",47420,966381,1139179,14.55,9.26,6.17,5.92,5.92
Aquatic Plants,51178,1057275,1278386,507.29,631.23,470.21,452.02,452.02
"Aquatic Products, Other",52570,1160712,1320249,519.62,638.42,475.08,456.65,456.65
Bananas,68496,1338880,1894890,53267.31,55046.76,54376.07,53008.82,55549.23
Barley and products,76321,1432410,2243002,25384.66,29153.44,24706.08,26176.98,31253.70
Beans,78001,1476680,2263509,19207.68,20315.77,19037.50,21351.42,20121.14
Beer,65975,1314720,1813728,41879.92,42053.67,42540.48,41962.92,41612.12
"Beverages, Alcoholic",65918,1313052,1807946,3067.16,2818.38,2834.92,3115.24,2979.21
"Beverages, Fermented",65203,1299273,1774758,50536.78,47447.92,45478.53,43958.75,46874.94
Bovine Meat,70033,1431044,1963251,22098.60,22766.42,22411.18,22612.86,23926.30
"Butter, Ghee",60516,1238480,1594919,1249.29,1165.69,1199.87,1116.68,1175.59
Cassava and products,73208,1385004,2081916,405442.57,410235.89,415730.20,401440.17,435862.14
Cephalopods,58593,1233636,1571763,423.03,496.95,503.64,532.14,532.07
Cereals - Excluding Beer,95370,2074170,2976719,851924.06,845669.36,875974.56,905221.25,903280.79
"Cereals, Other",79505,1489320,2326237,18689.11,18912.55,19877.56,20615.95,22125.96
"Citrus, Other",70239,1367122,1954812,14533.46,15188.91,15515.30,15650.97,15804.14
Cloves,53398,1064726,1420590,77.37,77.29,78.27,82.32,82.36
Cocoa Beans and products,70862,1398123,1998287,7166.65,7671.59,7510.86,8638.32,8353.83
Coconut Oil,69418,1330248,1959863,517.56,556.18,549.43,516.99,537.70
Coconuts - Incl Copra,74263,1410560,2104761,6568.33,6646.28,6577.23,6478.91,6526.12
Coffee and products,72724,1433350,2070618,3677.92,3849.99,4115.34,3861.45,4009.65
Cottonseed,44285,841911,1768564,8108.00,7998.00,8093.00,8623.00,8802.00
Cottonseed Oil,67319,1287500,1881106,1379.76,1507.90,1366.75,1403.25,1421.56
Cream,55778,1141088,1421946,237.52,233.37,267.84,228.95,271.61
Crustaceans,64831,1338260,1761859,734.07,732.86,717.30,834.82,833.61
Dates,64881,1278072,1771007,10183.80,11108.74,10904.81,11088.61,11454.52
Demersal Fish,62436,1292616,1677632,5845.93,6123.88,5691.28,6618.70,6616.23
Eggs,154150,3250703,4426246,20563.36,21431.48,20428.82,21749.74,20638.48
"Fats, Animals, Raw",79842,1636726,2341974,1596.09,1729.80,1614.01,1783.67,1707.11
"Fish, Body Oil",56619,1154115,1462871,170.51,193.73,167.09,219.65,219.65
"Fish, Liver Oil",48755,979264,1197204,38.13,6.36,15.87,48.02,48.02
"Fish, Seafood",71756,1583600,2039247,43240.02,43293.41,43727.14,44849.35,44810.20
Freshwater Fish,64920,1333563,1761607,13161.92,13195.86,13908.83,14258.00,14244.98
Fruits - Excluding Wine,79433,1725129,2313131,273559.54,282857.19,277458.49,284309.07,290381.46
"Fruits, Other",76833,1506750,2224160,53970.46,57504.33,57730.21,59463.60,61370.30
Grand Total,18060,391635,90990,119183.84,118937.92,118434.34,119264.82,119388.06
Grapefruit and products,69139,1340469,1896997,2359.01,2352.21,2129.03,2137.02,2449.18
Grapes and products (excl wine),70255,1367640,1946827,13820.84,14607.88,14235.15,14591.98,13992.75
Groundnut Oil,70147,1355444,1971148,5479.80,5561.17,5511.52,5389.20,5463.60
Groundnuts (Shelled Eq),82299,1577052,2457038,42384.73,42199.35,43962.23,44684.53,46513.58
Honey,69241,1413675,1908893,679.11,713.12,664.78,660.07,681.56
Infant food,59745,1197960,1547996,328.49,340.38,331.92,311.92,298.01
"Lemons, Limes and products",70391,1358240,1938946,3429.42,3667.51,3600.68,4191.49,4220.50
Maize Germ Oil,64256,1234196,1747258,874.59,950.64,1000.13,1075.37,865.77
Maize and products,91790,1727118,2832303,291731.71,287659.14,294568.76,323471.75,297383.10
"Marine Fish, Other",64234,1323956,1733842,3253.42,3153.59,3250.75,3136.63,3134.78
Meat,72011,1583334,2037234,65331.31,66042.60,66050.65,67833.55,70553.53
"Meat, Other",69390,1416730,1930240,5182.20,5287.66,5293.44,5324.82,5412.90
Milk - Excluding Butter,168482,3657276,5058264,268099.98,266446.14,272380.98,276703.90,281018.64
Millet and products,77725,1401969,2288150,40339.67,40459.94,43469.33,41836.61,49783.34
Miscellaneous,121457,2654213,3195541,6582.96,6803.24,6469.24,6921.83,6715.51
"Molluscs, Other",59450,1228548,1543765,147.51,134.91,156.34,157.34,157.20
Mutton & Goat Meat,65536,1338680,1780997,9661.64,9625.44,9731.22,9769.78,9769.46
Nuts and products,70304,1336724,1962812,6523.47,6939.31,6319.69,6875.08,6886.56
Oats,69915,1315868,1957915,726.54,930.02,844.96,902.97,1029.29
Offals,70523,1549070,1973858,7659.28,7841.07,7843.57,8252.88,8751.58
"Offals, Edible",70523,1439136,1973858,7659.28,7841.07,7843.57,8252.88,8751.58
Oilcrops,94222,2056578,2933349,158075.67,163097.03,161193.66,166985.23,180845.03
"Oilcrops Oil, Other",74081,1432644,2118276,5600.20,5398.90,5181.81,5925.84,5580.14
"Oilcrops, Other",79141,1506020,2406571,6410.95,6584.80,6689.05,6269.10,6464.42
Olive Oil,68333,1315800,1883123,1467.44,1711.65,1499.27,1484.14,1983.76
Olives (including preserved),64335,1225114,1727253,9002.41,12547.69,11028.51,9930.20,12824.75
Onions,67525,1298398,1848334,33467.52,36973.65,37435.12,39656.98,40608.41
"Oranges, Mandarines",73421,1425606,2075758,33363.64,33421.50,31442.59,34602.81,34471.68
Palm Oil,71538,1391580,2077827,26807.94,27229.24,25725.04,32462.95,32732.58
Palm kernels,35467,686616,1372593,50648.00,52524.00,53669.00,56218.00,58841.00
Palmkernel Oil,66182,1275120,1915385,1570.26,1408.94,1381.47,1517.36,1516.58
Peas,72290,1349910,2012632,2432.99,2472.35,2309.69,2425.43,2353.80
Pelagic Fish,70739,1472679,2031808,19998.64,19838.14,19957.99,19801.15,19779.84
Pepper,64603,1269840,1731589,137.74,137.04,147.84,142.76,141.51
Pigmeat,68591,1410228,1918369,5890.26,5914.61,5933.10,6099.27,6188.40
Pimento,65712,1288808,1785669,2481.19,2754.14,2894.98,2812.22,2847.67
Pineapples and products,70539,1377068,1968060,14363.66,14276.56,14568.95,15694.20,16120.73
Plantains,54725,1051632,1479569,64682.48,65037.18,63021.24,63619.19,65213.66
Population,12040,225090,261540,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Potatoes and products,86083,1622371,2582884,75754.48,78655.23,74097.50,74990.58,77793.56
Poultry Meat,69333,1418946,1937247,22472.52,22440.36,22681.72,23985.90,25257.39
Pulses,86362,1889239,2638522,56711.40,59361.19,61508.09,65535.31,64771.23
"Pulses, Other and products",83586,1595674,2515138,35061.63,36569.14,40138.81,41741.43,42264.26
Rape and Mustard Oil,65777,1271556,1849681,228.88,312.38,276.41,329.98,247.25
Rape and Mustardseed,71380,1355740,1995188,667.00,663.00,621.00,628.00,666.00
Rice and products,89260,1879350,2744539,155122.23,150657.00,161150.98,166354.09,167195.55
Ricebran Oil,33527,598792,1010165,0.00,0.00,0.00,0.00,0.00
"Roots, Other",72036,1378496,2091445,42001.37,42757.91,42883.23,43389.37,43797.46
Rye and products,63769,1192110,1788655,284.24,428.14,303.19,306.41,324.35
Sesame seed,71143,1365013,2121769,8044.24,6769.62,7819.98,7955.60,8492.35
Sesameseed Oil,65744,1230183,1814000,609.73,587.58,716.58,663.10,589.79
Sorghum and products,84070,1525908,2456864,86939.64,82725.53,91609.56,85468.93,91504.28
Soyabean Oil,70775,1362630,1986336,9033.32,10381.77,10151.87,10683.31,11422.03
Soyabeans,76891,1456350,2225300,15067.19,16412.47,15920.30,18574.99,24180.95
Spices,70582,1522883,1945922,4421.98,5059.08,6839.95,6801.63,6406.66
"Spices, Other",66306,1296050,1783586,1695.48,2068.57,3692.79,3744.19,3318.96
Starchy Roots,90330,1959318,2763138,792393.91,802578.22,823223.18,825497.34,855955.18
Stimulants,75449,1656774,2186289,13587.83,14180.97,14314.71,15119.56,15214.78
Sugar & Sweeteners,82006,1783217,2435532,78235.83,80214.74,80920.20,86952.63,87663.08
Sugar (Raw Equivalent),70517,1352344,2004572,69295.13,70675.27,71786.18,77413.80,78055.95
Sugar Crops,66146,1445276,2127345,322467.52,317423.30,314772.13,315572.36,326132.77
Sugar beet,33784,616491,1108508,40090.00,47240.00,47244.00,45332.00,44685.00
Sugar cane,59554,1133592,1913174,282380.51,270179.30,267526.12,270238.36,281447.76
Sugar non-centrifugal,18769,307461,526787,236.98,230.85,185.80,204.68,215.68
Sunflower seed,57326,999787,1677799,11136.14,10686.98,6749.09,7545.63,7500.39
Sunflowerseed Oil,70253,1348252,1957077,6126.70,4986.00,4901.51,6432.42,5996.97
Sweet potatoes,74062,1393150,2131142,68785.44,67762.36,69849.89,76488.54,77209.90
"Sweeteners, Other",77144,1464768,2244222,8034.54,8593.45,8277.40,8667.08,8701.86
Tea (including mate),65694,1280610,1759540,2716.24,2627.37,2652.44,2599.72,2834.23
Tomatoes and products,74112,1440954,2117921,68147.92,68981.37,62570.48,61712.96,63750.78
Treenuts,70304,1525888,1962812,6523.47,6939.31,6319.69,6875.08,6886.56
Vegetable Oils,76734,1675550,2228663,59740.35,60659.38,58312.01,67913.02,68401.90
Vegetables,78335,1712866,2295933,256648.34,264068.13,256219.45,259140.62,268337.49
"Vegetables, Other",77779,1518715,2275409,155038.96,158104.08,156218.90,157752.59,163987.21
Vegetal Products,18060,391905,90990,107145.19,107064.17,106792.72,107655.20,107775.39
Wheat and products,87073,1639683,2654934,232670.13,234710.51,239377.07,240047.62,242645.19
Wine,66206,1319535,1818328,4497.36,4251.81,3872.09,4178.02,4039.32
Yams,50798,970905,1525745,200396.96,203151.78,220626.20,229174.59,221272.09

### Result: 
    Total sum of Animal fats produced in 2014 is 209460.54
    Total sum of Animal fats produced in 2017 is 269617.53

In [14]:
df.groupby('Item').get_group('Animal fats').sum()

Area Code                                                   85279
Area            AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Item Code                                                 1882494
Item            Animal fatsAnimal fatsAnimal fatsAnimal fatsAn...
Element Code                                              2567303
Element         ProductionImport QuantityStock VariationExport...
Unit            1000 tonnes1000 tonnes1000 tonnes1000 tonnes10...
Y2014                                                   209460.54
Y2015                                                   200675.72
Y2016                                                   183314.22
Y2017                                                   269617.53
Y2018                                                   269648.27
dtype: object

## What is the mean and Standard deviation across the whole dataset for the year 2015 to 3 decimal places?

In [16]:
df.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

### Result:
    The mean across the whole dataset for year 2015 is 135.236
    The standard deviation across the whole dataset for year 2015 is 1603.404

## What is the total number and percentage of missing data in 2016 to 2 decimal places?

In [19]:
df.isnull().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [25]:
for col in df.columns:
    percentage_missing = np.mean(df[col].isnull())*100
    print('{} - {}%'.format(col,percentage_missing))

Area Code - 0.0%
Area - 0.0%
Item Code - 0.0%
Item - 0.0%
Element Code - 0.0%
Element - 0.0%
Unit - 0.0%
Y2014 - 2.6073544131401474%
Y2015 - 2.5400784339464746%
Y2016 - 2.5187470259094566%
Y2017 - 2.4711615772114928%
Y2018 - 2.356300149319856%

### Result:
    The total number and percentage of missing data in 2016 is 1535 and 2.52%

## Which year had the highest correlation with 'Element Code'?

In [35]:
df.corr()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Area Code,1.000000,-0.005159,-0.000209,0.006164,0.005472,0.005247,0.005006,0.005665
Item Code,-0.005159,1.000000,-0.024683,0.021722,0.020857,0.020109,0.021494,0.021314
Element Code,-0.000209,-0.024683,1.000000,0.024457,0.023889,0.023444,0.024254,0.024279
Y2014,0.006164,0.021722,0.024457,1.000000,0.994647,0.996081,0.995230,0.994872
Y2015,0.005472,0.020857,0.023889,0.994647,1.000000,0.995739,0.988048,0.988208
Y2016,0.005247,0.020109,0.023444,0.996081,0.995739,1.000000,0.992785,0.992757
Y2017,0.005006,0.021494,0.024254,0.995230,0.988048,0.992785,1.000000,0.998103
Y2018,0.005665,0.021314,0.024279,0.994872,0.988208,0.992757,0.998103,1.000000

In [36]:
df.corr()*100

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Area Code,100.000000,-0.515910,-0.020860,0.616411,0.547166,0.524714,0.500578,0.566540
Item Code,-0.515910,100.000000,-2.468327,2.172208,2.085737,2.010913,2.149439,2.131369
Element Code,-0.020860,-2.468327,100.000000,2.445682,2.388920,2.344400,2.425401,2.427857
Y2014,0.616411,2.172208,2.445682,100.000000,99.464736,99.608122,99.522984,99.487166
Y2015,0.547166,2.085737,2.388920,99.464736,100.000000,99.573892,98.804787,98.820845
Y2016,0.524714,2.010913,2.344400,99.608122,99.573892,100.000000,99.278463,99.275667
Y2017,0.500578,2.149439,2.425401,99.522984,98.804787,99.278463,100.000000,99.810327
Y2018,0.566540,2.131369,2.427857,99.487166,98.820845,99.275667,99.810327,100.000000

### Result:
    2014 (Y2014) had the highest correlation with Element Code of 2.45%

## What year had the highest sum of Import Quantity?

In [40]:
df.groupby('Element').sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,708993,14197445,28068795,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,11840553,26026133,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,13535000,3435732,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,3538507,7282199,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,13285035,25406622,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,13511060,3329296,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,13185401,3163725,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,13795966,28834929,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,5424803,10292107,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,4729749,8926728,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,5350416,10313310,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,10450053,21388191,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,13535000,3385502,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,12421089,24066350,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,2035933,4211574,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,11329527,21464704,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,112545,22995,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,1486528,2869905,416.00,349.00,89.00,91.00,90.00

### Result:
    2017 (Y2017, 294559.09) has the highest sum of Import Quantity

## What is the total number of the sum of production in 2014?

In [41]:
df.groupby('Element').sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,708993,14197445,28068795,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,11840553,26026133,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,13535000,3435732,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,3538507,7282199,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,13285035,25406622,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,13511060,3329296,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,13185401,3163725,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,13795966,28834929,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,5424803,10292107,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,4729749,8926728,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,5350416,10313310,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,10450053,21388191,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,13535000,3385502,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,12421089,24066350,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,2035933,4211574,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,11329527,21464704,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,112545,22995,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,1486528,2869905,416.00,349.00,89.00,91.00,90.00

### Result:
    The total number of Production in 2014 is 1931287.75

## Which of these elements had the highest sum in 2018?

In [55]:
#select columns 'Y2018' and 'Element'

df_y2018_element = df[['Y2018','Element']]

In [63]:
df_y2018_element.groupby('Element').sum().sort_values(by='Y2018',ascending=False)

                                             Y2018
Element
Domestic supply quantity                2161192.10
Production                              2075072.89
Food                                    1303841.28
Total Population - Both sexes           1140605.00
Food supply (kcal/capita/day)            455261.00
Processing                               308429.00
Import Quantity                          287997.09
Feed                                     233489.68
Export Quantity                          181594.80
Losses                                   163902.00
Other uses (non-food)                     91300.97
Food supply quantity (kg/capita/yr)       49056.85
Residuals                                 34864.00
Seed                                      25263.14
Stock Variation                           20577.91
Protein supply quantity (g/capita/day)    11833.56
Fat supply quantity (g/capita/day)        10258.69
Tourist consumption                          90.00

### Result:
    Domestic supply quantity (2161192.10) is the "Element" that had the highest sum 2018.

## Which of these elements had the 3rd lowest sum in 2018?

In [64]:
df_y2018_element.groupby('Element').sum().sort_values(by='Y2018',ascending=True)

                                             Y2018
Element
Tourist consumption                          90.00
Fat supply quantity (g/capita/day)        10258.69
Protein supply quantity (g/capita/day)    11833.56
Stock Variation                           20577.91
Seed                                      25263.14
Residuals                                 34864.00
Food supply quantity (kg/capita/yr)       49056.85
Other uses (non-food)                     91300.97
Losses                                   163902.00
Export Quantity                          181594.80
Feed                                     233489.68
Import Quantity                          287997.09
Processing                               308429.00
Food supply (kcal/capita/day)            455261.00
Total Population - Both sexes           1140605.00
Food                                    1303841.28
Production                              2075072.89
Domestic supply quantity                2161192.10

### Result:
    Protein supply quantity (g/capita/day) (11833.56) is the "Element" that had the 3rd lowest sum in 2018

## What is the total Import Quantity in Algeria in 2018?

In [98]:
dfx = df[['Element', 'Area', 'Y2018']]

In [87]:
dfx.head()

                                  Element     Area     Y2018
0           Total Population - Both sexes  Algeria  42228.00
1                Domestic supply quantity  Algeria      0.00
2           Food supply (kcal/capita/day)  Algeria   3322.00
3  Protein supply quantity (g/capita/day)  Algeria     91.83
4      Fat supply quantity (g/capita/day)  Algeria     77.28

In [106]:
dfx1 = dfx.groupby(['Element','Area']).sum()

In [110]:
dfx1

                                                                        Y2018
Element                                Area
Domestic supply quantity               Algeria                       90023.42
                                       Angola                        59590.22
                                       Benin                         31447.90
                                       Botswana                       3045.85
                                       Burkina Faso                  25705.16
                                       Cabo Verde                      731.00
                                       Cameroon                      64009.74
                                       Central African Republic       5567.06
                                       Chad                          15489.73
                                       Comoros                          19.95
                                       Congo                          8524.55
                                       Cï¿½te d'Ivoire                 55557.64
                                       Djibouti                       2760.96
                                       Egypt                        248477.72
                                       Eswatini                      13158.81
                                       Ethiopia                     107850.72
                                       Ethiopia PDR                      0.00
                                       Gabon                          4608.75
                                       Gambia                         2221.89
                                       Ghana                        100558.45
                                       Guinea                        25292.85
                                       Guinea-Bissau                  2049.58
                                       Kenya                         67202.58
                                       Lesotho                        2062.73
                                       Liberia                        4998.99
                                       Madagascar                    32596.87
                                       Malawi                        50937.37
                                       Mali                          40795.02
                                       Mauritania                    22053.08
                                       Mauritius                      8290.36
                                       Morocco                       86458.07
                                       Mozambique                    42581.75
                                       Namibia                        4019.66
                                       Niger                         31258.84
                                       Nigeria                      428323.32
                                       Rwanda                        17426.52
                                       Sao Tome and Principe           349.73
                                       Senegal                       19374.64
                                       Seychelles                       10.68
                                       Sierra Leone                  12753.68
                                       South Africa                 126493.86
                                       Sudan                         65451.77
                                       Sudan (former)                    0.00
                                       Togo                          10000.22
                                       Tunisia                       31347.90
                                       Uganda                        54617.10
                                       United Republic of Tanzania   92239.88
                                       Zambia                        24994.80
                                       Zimbabwe                      17860.73
Export Quantity                        Algeria                         811.54
                                       Angola                         7962.28
                                       Benin                           729.44
                                       Botswana                        101.68
                                       Burkina Faso                   1088.16
                                       Cabo Verde                       42.99
                                       Cameroon                       1078.16
                                       Central African Republic          0.26
                                       Chad                             36.22
                                       Comoros                           0.00
                                       Congo                            25.03
                                       Cï¿½te d'Ivoire                  8120.48
                                       Djibouti                       1084.00
                                       Egypt                          9420.24
                                       Eswatini                       1262.04
                                       Ethiopia                       2138.78
                                       Ethiopia PDR                      0.00
                                       Gabon                            16.30
                                       Gambia                         1390.59
                                       Ghana                          4284.86
                                       Guinea                          191.61
                                       Guinea-Bissau                   156.00
                                       Kenya                          3086.45
                                       Lesotho                          80.96
                                       Liberia                          65.48
                                       Madagascar                      535.81
                                       Malawi                          597.18
                                       Mali                            165.30
                                       Mauritania                    36217.88
                                       Mauritius                      3387.12
                                       Morocco                       42429.99
                                       Mozambique                     1394.81
                                       Namibia                        1712.92
                                       Niger                          2017.22
                                       Nigeria                        1233.02
                                       Rwanda                          383.64
                                       Sao Tome and Principe            10.00
                                       Senegal                        4451.63
                                       Seychelles                      205.14
                                       Sierra Leone                    143.90
                                       South Africa                  31630.62
                                       Sudan                          1632.13
                                       Sudan (former)                    0.00
                                       Togo                            809.35
                                       Tunisia                        1649.87
                                       Uganda                         4095.70
                                       United Republic of Tanzania    2289.77
                                       Zambia                         1011.54
                                       Zimbabwe                        416.71
Fat supply quantity (g/capita/day)     Algeria                         309.09
                                       Angola                          230.90
                                       Benin                           207.82
                                       Botswana                        261.12
                                       Burkina Faso                    264.29
                                       Cabo Verde                      264.32
                                       Cameroon                        217.53
                                       Central African Republic        242.76
                                       Chad                            211.53
                                       Congo                           181.82
                                       Cï¿½te d'Ivoire                   237.96
                                       Djibouti                        247.43
                                       Egypt                           238.72
                                       Eswatini                        189.94
                                       Ethiopia                        108.49
                                       Gabon                           211.75
                                       Gambia                          241.96
                                       Ghana                           164.21
                                       Guinea                          274.89
                                       Guinea-Bissau                   245.35
                                       Kenya                           191.54
                                       Lesotho                         211.10
                                       Liberia                         196.34
                                       Madagascar                       96.43
                                       Malawi                          161.35
                                       Mali                            235.33
                                       Mauritania                      268.78
                                       Mauritius                       377.28
                                       Morocco                         284.16
                                       Mozambique                      195.06
                                       Namibia                         219.81
                                       Niger                           209.32
                                       Nigeria                         218.84
                                       Rwanda                          123.56
                                       Sao Tome and Principe           286.54
                                       Senegal                         243.21
                                       Sierra Leone                    199.86
                                       South Africa                    331.72
                                       Sudan                           263.63
                                       Togo                            197.24
                                       Tunisia                         379.37
                                       Uganda                          200.36
                                       United Republic of Tanzania     214.16
                                       Zambia                          193.83
                                       Zimbabwe                        207.99
Feed                                   Algeria                       10668.00
                                       Angola                         7859.66
                                       Benin                          4662.54
                                       Botswana                         28.04
                                       Burkina Faso                   1031.50
                                       Cabo Verde                       48.00
                                       Cameroon                       4857.24
                                       Central African Republic          5.00
                                       Chad                           1150.00
                                       Comoros                           0.00
                                       Congo                            39.66
                                       Cï¿½te d'Ivoire                  6410.00
                                       Djibouti                        298.00
                                       Egypt                         25158.30
                                       Eswatini                         82.00
                                       Ethiopia                       3669.00
                                       Ethiopia PDR                      0.00
                                       Gabon                           573.00
                                       Gambia                          114.02
                                       Ghana                         14730.28
                                       Guinea                         4090.00
                                       Guinea-Bissau                    22.00
                                       Kenya                          1496.28
                                       Lesotho                         142.00
                                       Liberia                         118.00
                                       Madagascar                     2133.60
                                       Malawi                        17802.40
                                       Mali                           3369.30
                                       Mauritania                       63.34
                                       Mauritius                       501.18
                                       Morocco                       13679.87
                                       Mozambique                     2485.17
                                       Namibia                         119.40
                                       Niger                          2389.00
                                       Nigeria                       73064.53
                                       Rwanda                           96.00
                                       Sao Tome and Principe             0.00
                                       Senegal                         381.41
                                       Seychelles                        4.14
                                       Sierra Leone                   2170.00
                                       South Africa                  12413.42
                                       Sudan                          1887.00
                                       Sudan (former)                    0.00
                                       Togo                           1171.62
                                       Tunisia                        5621.70
                                       Uganda                          297.04
                                       United Republic of Tanzania    4495.06
                                       Zambia                         1950.66
                                       Zimbabwe                        141.32
Food                                   Algeria                       63736.33
                                       Angola                        37256.56
                                       Benin                         16209.34
                                       Botswana                       2378.80
                                       Burkina Faso                  20525.63
                                       Cabo Verde                      572.99
                                       Cameroon                      35235.51
                                       Central African Republic       4457.06
                                       Chad                           9846.69
                                       Comoros                          12.45
                                       Congo                          6281.89
                                       Cï¿½te d'Ivoire                 32660.63
                                       Djibouti                        790.96
                                       Egypt                        145135.30
                                       Eswatini                       1217.81
                                       Ethiopia                      78564.70
                                       Ethiopia PDR                      0.00
                                       Gabon                          2906.75
                                       Gambia                         1618.88
                                       Ghana                         52540.78
                                       Guinea                        14310.85
                                       Guinea-Bissau                  1491.58
                                       Kenya                         50504.48
                                       Lesotho                        1817.72
                                       Liberia                        3802.99
                                       Madagascar                    22116.21
                                       Malawi                        23295.97
                                       Mali                          25110.72
                                       Mauritania                     4175.50
                                       Mauritius                      1348.03
                                       Morocco                       48698.59
                                       Mozambique                    29772.57
                                       Namibia                        2751.26
                                       Niger                         23049.84
                                       Nigeria                      243467.65
                                       Rwanda                        15552.52
                                       Sao Tome and Principe           254.13
                                       Senegal                       13763.22
                                       Seychelles                        5.58
                                       Sierra Leone                   8444.68
                                       South Africa                  61781.13
                                       Sudan                         41857.77
                                       Sudan (former)                    0.00
                                       Togo                           7229.60
                                       Tunisia                       18901.69
                                       Uganda                        41420.05
                                       United Republic of Tanzania   65741.38
                                       Zambia                        12405.14
                                       Zimbabwe                       8821.37
Food supply (kcal/capita/day)          Algeria                       13288.00
                                       Angola                         9538.00
                                       Benin                         11023.00
                                       Botswana                       9365.00
                                       Burkina Faso                  10951.00
                                       Cabo Verde                    10164.00
                                       Cameroon                      10929.00
                                       Central African Republic       7141.00
                                       Chad                           8457.00
                                       Congo                          9141.00
                                       Cï¿½te d'Ivoire                 11110.00
                                       Djibouti                      10779.00
                                       Egypt                         13166.00

### Result:
    The total Import Quantity in Algeria in 2018 is 36238.29

## What is the total number of unique countries in the dataset?

In [168]:
df['Area'].unique()

array(['Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso',
       'Cabo Verde', 'Cameroon', 'Central African Republic', 'Chad',
       'Comoros', 'Congo', "Cï¿½te d'Ivoire", 'Djibouti', 'Egypt',
       'Eswatini', 'Ethiopia', 'Ethiopia PDR', 'Gabon', 'Gambia', 'Ghana',
       'Guinea', 'Guinea-Bissau', 'Kenya', 'Lesotho', 'Liberia',
       'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mauritius',
       'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Rwanda',
       'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone',
       'South Africa', 'Sudan', 'Sudan (former)', 'Togo', 'Tunisia',
       'Uganda', 'United Republic of Tanzania', 'Zambia', 'Zimbabwe'],
      dtype=object)

In [164]:
df['Area'].nunique()

49

### Result:
    The total number of unique countries in the dataset is 49